apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: mhreddy-v1-test-8htl9
    machine.openshift.io/cluster-api-machine-role: master
    machine.openshift.io/cluster-api-machine-type: master
    machine.openshift.io/instance-type: Standard_D8s_v3
    machine.openshift.io/region: eastus
    machine.openshift.io/zone: "3"
  name: mhreddy-v1-test-8htl9-master-2
  namespace: openshift-machine-api
spec:
  metadata: {}
  providerSpec:
    value:
      apiVersion: azureproviderconfig.openshift.io/v1beta1
      credentialsSecret:
        name: azure-cloud-credentials
        namespace: openshift-machine-api
      image:
        offer: aro4
        publisher: azureopenshift
        resourceID: ""
        sku: aro_44
        version: 44.81.20200425
      kind: AzureMachineProviderSpec
      location: eastus
      metadata: {}
      networkResourceGroup: v4-eastus
      osDisk:
        diskSizeGB: 1024
        managedDisk:
          storageAccountType: Premium_LRS
        osType: Linux
      publicIP: false
      resourceGroup: aro-mhreddy-v1-test
      subnet: mhreddy-v1-test-master
      userDataSecret:
        name: master-user-data
      vmSize: Standard_D8s_v3
      vnet: dev-vnet
      zone: "1"